name: hds_forecast
channels:
  - conda-forge
  - defaults
dependencies:
  - jupyterlab=2.1.2
  - matplotlib=3.2.1
  - notebook=6.0.3
  - numpy=1.18.1
  - pandas=1.0.3
  - pip=20.0.2
  - python=3.7.7
  - pytorch=1.4.0
  - scipy=1.4.1
  - seaborn=0.10.0
  - statsmodels=0.11.1
  - tensorflow=2.0.0
  - pip:
    - pmdarima==1.6.0
    - scikit-learn==0.23.0
    - fbprophet==0.6
    - forecast-tools==0.1.5
